---
layout:		post
category:	"lua"
title:		"Lua异常处理，用pcall安全地调用一个函数"
tags:		[lua]
---
- Content
{:toc}

参考：[Lua 5\.3 参考手册](https://cloudwu.github.io/lua53doc/manual.html#3.4.2)

如果在调用一个函数时，会担心这个函数出错，则可以使用pcall来调用。
```lua
func1 = function(s)
    return s
end

func2 = function(s)
    t.a = nil
    return s
end

status,result = pcall(func1, "func1")
print(status,result)

status,result = pcall(func2, "func2")
print(status,result)
```

- func1执行正确返回：true func1
- func2因为有错误返回：false 1.lua:8: attempt to index global 't' (a nil value)

